Fix 1234600 depends if value is empty
Elastic-Suite/gally-admin pull request #105
Opened 2023-07-05 08:18 UTC by Ponefar

| Q             | A
| ------------- | ---
| Branch?       | master for features / current stable version branch for bug fixes
| Tickets       | #... 
| License       | OSL-3.0

2023-07-05 12:48 UTC, tonai requested changes

2023-07-05 12:48 UTC, tonai commented on packages/components/src/services/form.ts
> +    )
ça fait beaucoup de négation et c'est difficilement compréhensible comme test.
Si on test les différentes possibilité on arrive au tableau suivant:

fieldValue | value     | return
-----------|-----------|-------
undefined  | undefined | true
undefined  | 1         | true
1          | undefined | false
1          | 2         | true
1          | 1         | false

Ce qui peut se résumer à:
```js
return (fieldValue === undefined || (value !== fieldValue && value !== undefined));
```

2023-07-05 12:48 UTC, tonai commented on packages/components/src/services/form.ts
> +    )
Ce qui peut se retrouver en sachant qu'en logique `!(a && b)` équivaut à `(!a || !b)`

2023-07-05 14:27 UTC, Ponefar commented on packages/components/src/services/form.ts
> +    )
hum en effet, merci

2023-07-06 06:53 UTC, tonai approved these changes

2023-07-10 11:17 UTC, merged