Synonym Design System Draft
Elastic-Suite/gally-admin pull request #108
Opened 2023-07-10 16:29 UTC by botisSmile

| Q             | A
| ------------- | ---
| Branch?       | master for features / current stable version branch for bug fixes
| Tickets       | #... 
| License       | OSL-3.0

2023-08-30 08:11 UTC, tonai commented on packages/components/src/components/atoms/form/Expansion.tsx
> +  function iExpansionsFormattedToIExpansions(
C'est un détail mais si tu n'utilises pas de variables de la fonction parente dans cette fonction (comme une closure) alors tu peux extraire cette fonction de la fonction Parente (Expansion).
(tu n'utilises pas de variables du parent, puisque tu prends la variable `expansions` en paramètre)
Cela évite de devoir recréer la fonction à chaque render.
Tu peux simplement extraire la function et la déclarer avant le composant Expansion.

2023-08-30 08:16 UTC, tonai commented on packages/components/src/components/atoms/form/Expansion.tsx
> +      expansions.splice(index, 1)
En React il faut éviter de faire des mutations.
`splice` ça modifie la variables `expansions`ce qui peut avoir des conséquence.
Il vaut mieux utiliser `filter` pour recréer un nouveau tableau.
Ou tu crées un clone avant.

2023-08-30 08:16 UTC, tonai commented on packages/components/src/components/atoms/form/Expansion.tsx
> +      expansions.push({
Eviter les mutations en React.
Utilise plutôt `concat` pour créer un nouveau tableau.
Ou tu crées un clone avant.

2023-08-30 08:17 UTC, tonai commented on packages/components/src/components/atoms/form/Expansion.tsx
> +      expansions[index].referenceTerm = referenceTerm
Eviter les mutations en React.
Privilégie un `map` pour créer un nouveau tableau.
Ou tu crées un clone avant.

2023-08-30 08:18 UTC, tonai commented on packages/components/src/components/atoms/form/Expansion.tsx
> +      expansions[index].terms = []
Eviter les mutations.
Probablement utiliser un `map` ici.
Ou tu crées un clone avant.

2023-08-30 08:21 UTC, tonai commented on packages/components/src/components/atoms/form/Synonym.tsx
> +function Synonym(props: IProps): JSX.Element {
Mêmes remarques que pour le composant `Expansion`:
* extraire les fonctions qui ne sont pas des closures
* éviter les mutations

2023-08-30 08:30 UTC, tonai commented on packages/components/src/components/molecules/format/FormatRowArray.tsx
> +  })
Pour info tu peux aussi utiliser `reduce` pour ça:
```js
const maxChar = values.reduce((acc, item, index) => {
  if (index < multipleValueFormat.maxCount) {
    acc += item.length
  }
  return acc;
}, 0)
```
Ou en one liner:
```js
const maxChar = values.reduce(
  (acc, item, index) => index < multipleValueFormat.maxCount ? acc + item.length : acc,
  0
)
```

2023-08-30 08:33 UTC, tonai commented on packages/components/src/components/stateful-pages/ResourceForm/ResourceForm.tsx
> +    checkExpansionsValidity(resource, data) &&
C'est un peu embêtant d'avoir de la logique spécifique aux synonymes et expansions ici, mais je suppose que c'est quelque chose qui changera si on change le système de validation pour utiliser la validation HTML.

2023-09-04 15:28 UTC, botisSmile commented on packages/components/src/components/stateful-pages/ResourceForm/ResourceForm.tsx
> +    checkExpansionsValidity(resource, data) &&
Oui c'est bien ça, on déplacera ces fonctions au niveau des composants, une fois le nouveau système des erreurs mis en place.

2023-09-06 12:52 UTC, tonai requested changes

2023-09-06 16:05 UTC, botisSmile commented on packages/components/src/components/molecules/format/FormatRowArray.tsx
> +    <div>
oui il est necessaire pour le bon affichage du composant, j'ai créé ce composant à partir de codes qui existainent déjà et qui étaient dupliqués

2023-09-06 16:06 UTC, botisSmile commented on packages/components/src/components/atoms/format/FormatArray.tsx
> +    <div>
idem

2023-09-07 15:38 UTC, tonai approved these changes

2023-09-13 13:51 UTC, merged