Fix 1246196 messages error for request type
Elastic-Suite/gally-admin pull request #136
Opened 2023-08-09 14:34 UTC by Ponefar

| Q             | A
| ------------- | ---
| Branch?       | master for features / current stable version branch for bug fixes
| Tickets       | #... 
| License       | OSL-3.0

2023-08-10 13:16 UTC, botisSmile requested changes

2023-08-29 09:50 UTC, tonai approved these changes

2023-08-29 09:56 UTC, tonai requested changes

2023-08-29 09:56 UTC, tonai commented on packages/components/src/components/stateful-pages/ResourceForm/ResourceForm.tsx
> +  }
Fonction inutile.
En plus il s'agit pas d'une simple function, mais d'un hook custom.
Du coup tu crées un hook custom à chaque render du composant.
Alors que tu peux tout simplement faire:
```js
const [requestTypeOptionsApi] = useApiList<IRequestTypesOptions>(
  listUrlRequestTypeConfigurations?.requestTypeOptionsApi
)
```

2023-08-29 09:56 UTC, tonai commented on packages/components/src/services/form.ts
>    // eslint-disable-next-line react-hooks/rules-of-hooks
Commentaire eslint à supprimer.
Il ne faut pas briser la règles des hooks sous causes de bugs potentiels.

2023-09-04 17:07 UTC, tonai requested changes

2023-09-04 17:07 UTC, tonai commented on packages/components/src/components/atoms/form/RequestTypeItem.tsx
> +      // Ce nouvel objet permet de réinitialiser les valeurs du tableau du limitations lorsqu'on clique sur la checkbox.
Les commentaires doivent être en Anglais.

2023-09-04 17:07 UTC, tonai commented on packages/components/src/components/organisms/CustomForm/CustomForm.tsx
> +                    value={{ field, data }}
Tu as déjà accès à `data` dans la props `data`.
Tu ne devrais peut-être pas merger `{...field}` non plus puisque tu en as besoin, tu devrais plutôt passer `field={field}`.
Du coup tu aurais dans `FormFieldGuesser`:
```tsx
function FormFieldGuesser(props: IFormFieldGuesserProps): JSX.Element {
  const { data, field, ...fieldProps } = props;
  const value = useValue(field, data);
  return (
    <FieldGuesser {...field} {...fieldProps} value={value} />
  )
}
```

2023-09-04 17:07 UTC, tonai commented on packages/components/src/services/form.ts
> +export function useValue(
`useValue` c'est un peu trop générique, plutôt `useFormValue`.

2023-09-06 12:42 UTC, tonai approved these changes

2023-09-06 14:19 UTC, merged