fix: error when catalog change - ESPP_663
Elastic-Suite/gally-admin pull request #28
Opened 2023-01-24 03:03 UTC by Ponefar

| Q             | A
| ------------- | ---
| Branch?       | master for features / current stable version branch for bug fixes
| Tickets       | #... 
| License       | OSL-3.0

2023-01-26 08:47 UTC, tonai requested changes

2023-01-26 08:47 UTC, tonai commented on packages/components/src/pages/admin/merchandize/categories.tsx
> +  }, [fetchApi, selectedCategoryItem?.id, catConfResource.url])
Il ne faut pas supprimer les dépendances d'un `useEffect`.
Que se passe-t-il maintenant quand tu modifies les filtres ?

2023-01-26 16:57 UTC, tonai requested changes

2023-01-26 16:57 UTC, tonai commented on packages/components/src/pages/admin/merchandize/categories.tsx
> +  }, [fetchApi, selectedCategoryItem?.id, catConfResource.url, categories])
ça va marcher parce que si `filters` change alors `categories` change et donc ici ça trigger le `useEffect`.
Mais dans ce cas tu peux aussi ajouter `filters` dans les dépendances du `useEffect`, ça ne change rien.
Et tu supprimes le commentaire eslint.
Les règles eslint sont là pour qu'on les respecte au maximum.

2023-01-27 14:35 UTC, tonai commented on packages/components/src/pages/admin/merchandize/categories.tsx
> +  }, [fetchApi, selectedCategoryItem?.id, catConfResource.url, categories])
Je ne vois pas de changements suite à mon dernier commentaire.

2023-02-08 11:52 UTC, botisSmile approved these changes

2023-02-08 16:08 UTC, merged