fix: update ESPP_700-textFieldTags
Elastic-Suite/gally-admin pull request #41
Opened 2023-02-10 16:50 UTC by Ponefar

| Q             | A
| ------------- | ---
| Branch?       | master for features / current stable version branch for bug fixes
| Tickets       | #... 
| License       | OSL-3.0

2023-02-13 09:16 UTC, tonai requested changes

2023-02-13 09:16 UTC, tonai commented on packages/components/src/components/atoms/form/TextFieldTags.tsx
> +    onChangeInput,
@Ponefar Pourquoi avoir `onChange` et `onChangeInput` ?
Tu ne peux pas avoir un seul `onChange` ?

2023-02-13 09:16 UTC, tonai commented on packages/components/src/components/atoms/form/TextFieldTags.tsx
> +  ) => void
A priori ton `onChange` doit renvoyer la liste de tout les tags, pas seulement celui qui a été ajouté/retiré.
Comme ça tu peux utiliser ton composant de cette manière:
```jsx
const [value, setValue] = useState([]);
return (<TextFieldTags value={value} onChange={setValue}/>);
```

2023-02-13 09:16 UTC, tonai commented on packages/components/src/components/atoms/form/TextFieldTags.tsx
> +          )}
ça me semble étrange de ne pas afficher le champ `InputText` quand il est `disabled`.
J'aurais plutôt passer le `disabled` au champ `InputText`: `<InputText disabled={disabled} ... />`
C'est plus cohérent en terme d'UX.

2023-02-13 09:16 UTC, tonai commented on packages/components/src/components/atoms/form/TextFieldTags.tsx
> +                size="small"
Le small en dur est pas ouf => il faut en faire une props (ne mets pas `small` en valeur par défaut non plus ça n'a pas de sens par rapport à l'ensemble des autres formulaires)

2023-02-13 09:16 UTC, tonai commented on packages/components/src/components/atoms/form/TextFieldTags.tsx
> +              />
ça ne serait pas plus simple de gèrer une props `disabled` sur le composant `Chip` ?

2023-02-13 09:16 UTC, tonai commented on packages/shared/src/types/index.ts
> +export * from './boost'
Je comprend pas pourquoi ce fichier s'appelle `boost`.

2023-02-13 09:16 UTC, tonai commented on packages/components/src/components/atoms/form/TextFieldTags.stories.tsx
> +  }
quand je vois toutes ces fonctions je me dis que ton composant n'est pas du  tout simple à utiliser.
Je pense qu'il y a des choses que du devrait pouvoir déplacer dans le composant `TextFieldTags`.
On veut pourvoir faire au final:
```jsx
const [value, setValue] = useState([]);
return (<TextFieldTags value={value} onChange={setValue}/>);
```

2023-02-13 09:25 UTC, Ponefar commented on packages/components/src/components/atoms/form/TextFieldTags.tsx
> +    onChangeInput,
le onChange c'est lorsqu'on selectionne un item dans la dropDown
le onChangeInput c'est un object afin de gérer l'input du textFieldTags lorsqu'il y en a plusieurs

2023-02-13 09:27 UTC, Ponefar commented on packages/components/src/components/atoms/form/TextFieldTags.tsx
> +          )}
Avec Léa on s'est dit qu'il fallait reprendre le même disabled que celui des dropDown.

2023-02-14 12:51 UTC, Ponefar commented on packages/components/src/components/atoms/form/TextFieldTags.tsx
> +  ) => void
?

2023-02-15 08:27 UTC, tonai requested changes

2023-02-15 08:27 UTC, tonai commented on packages/components/src/components/atoms/Chip/Chip.tsx
> +  const Component = disabled ? CustomChipDisabled : StyledChip
En fait tu n'as pas besoin de faire ça.
Tu peux récupérer le `disabled` dans la définition du styled component.
De la même manière que tu récupère le `theme`.
Du coup logiquement tu peux tout faire dans `StyledChip`.
Vérifie aussi que tu n'as pas de warning dans la console, ça arrive parfois quand on ajoute de nouvelle props à un composant MUI.

2023-02-15 08:27 UTC, tonai commented on packages/components/src/components/atoms/form/TextFieldTags.stories.tsx
> +      event.preventDefault()
Le `event.preventDefault()` est déjà fait dans le composant.
Ici tu n'a juste à faire `onChange={setData}` sur le composant.

2023-02-15 08:27 UTC, tonai commented on packages/components/src/components/atoms/form/TextFieldTags.stories.tsx
> +}
Cette variante n'est pas très utile.
D'autant plus que tu as déjà la props `disabled` dans `Default` donc tu peux facilement tester ce cas là.

2023-02-15 08:27 UTC, tonai commented on packages/components/src/components/atoms/form/TextFieldTags.tsx
> +                }}
Je suis pas trop fan de la props `sx`, car c'est moins performant que du style dans un styled component.

2023-02-16 09:07 UTC, merged