fix: create new textFieldTagsMultiple
Elastic-Suite/gally-admin pull request #51
Opened 2023-03-02 20:18 UTC by Ponefar

| Q             | A
| ------------- | ---
| Branch?       | master for features / current stable version branch for bug fixes
| Tickets       | #... 
| License       | OSL-3.0

2023-03-03 12:57 UTC, tonai requested changes

2023-03-03 12:57 UTC, tonai commented on packages/components/src/components/atoms/form/TextFieldTagsMultiple.stories.tsx
> +  }
tes 2 fonctions `transformedValue` et `onChange` doivent se trouver dans le composant.
Et tu peux passer `textOperatorOptions` via les args.
Dans le storybook l'usage doit être simple:
```tsx
const Template: ComponentStory<typeof TextFieldTagsComponentMultiple> = (
  args
) => {
  const [value, setValue] = useState<ITransformedLimitations>(transformedValue(searchLimitations))
  return (
    <TextFieldTagsComponentMultiple
      {...args}
      value={value}
      onChange={setValue}
    />
  )
}
```

2023-03-03 12:57 UTC, tonai commented on packages/components/src/components/atoms/form/TextFieldTagsMultiple.stories.tsx
> +  disabled: true,
Ajoute `options: textOperatorOptions` ici

2023-03-03 12:57 UTC, tonai commented on packages/components/src/components/atoms/form/TextFieldTagsMultiple.tsx
> +export interface ITextFieldTag extends ITextFIeldTagsForm {
Le nom de l'interface pour les props est soit `IProps` soit `ITextFieldTagsMultipleProps` (`I[nom du composant]Props`)

2023-03-03 12:57 UTC, tonai commented on packages/components/src/components/atoms/form/TextFieldTagsMultiple.tsx
> +  value: ITransformedLimitations
```suggestion
  value: ILimitations[]
```

2023-03-03 12:57 UTC, tonai commented on packages/components/src/components/atoms/form/TextFieldTagsMultiple.tsx
> +  onChange: (operator: string | string[], data?: string[] | string) => void
```suggestion
  onChange: (value: ILimitations[]) => void
```

2023-03-03 12:57 UTC, tonai commented on packages/components/src/components/atoms/form/TextFieldTagsMultiple.tsx
> +    })
Si tu veux tu peux simplifier l'écriture:
```js
const optionsListAvailable: IOptions = options.map(
  (item) => value[item.value] ? { ...item, disabled: true } : item
)
```

2023-03-03 12:57 UTC, tonai commented on packages/components/src/components/atoms/form/TextFieldTagsMultiple.stories.tsx
> +const textOperatorOptions: IOptionsTags[] = [
Pas besoin de typage spécifique ici, réutilise le typage `IOptions` qui existe déjà:
```suggestion
const textOperatorOptions: IOptions = [
```

2023-03-03 12:57 UTC, tonai commented on packages/components/src/components/atoms/form/TextFieldTagsMultiple.tsx
> +  }, [optionsListAvailable, optionDefault])
J'ai du mal à comprendre ce que fais ce code.
Il faut que tu nommes mieux tes variables.

2023-03-03 12:57 UTC, tonai commented on packages/components/src/components/atoms/form/TextFieldTagsMultiple.tsx
> +          Object.entries(value).map((item) => {
Si tu utilises `Object.entries`, destructure tout de suite ce que tu appelle `item` pour directement récupérer la clé et la valeur:
```suggestion
          Object.entries(value).map(([key, value]) => {
```

2023-03-03 14:45 UTC, Ponefar commented on packages/components/src/components/atoms/form/TextFieldTagsMultiple.tsx
> +  }, [optionsListAvailable, optionDefault])
ce code permet de selectionner une option disabled (qui n'est pas disabled)

2023-03-06 09:15 UTC, tonai requested changes

2023-03-06 09:15 UTC, tonai commented on packages/components/src/components/atoms/form/TextFieldTagsMultiple.tsx
> +  function onChangeModifiedValue(
Ici tu as fait une seule fonction qui gère tout les cas mais je pense pas que ce soit la meilleur façon de faire.
Parce que passer un array juste pour gérer le cas de l'ajout d'une ligne c'est pas terrible (le fait que ce soit un array n'apporte rien si ce n'est juste pour le premier test).
Tu peux utiliser utiliser une fonction différente pour chacun des cas avec un nom de fonction qui va bien.
Tu as potentiellement 4 cas à gérer:
* l'ajout d'une nouvelle "ligne"
* la suppression d'une "ligne"
* la modification de l'opérateur
* la modification de la valeur

ça peut ressembler à ça:
```js
  function addItem(operator: string): void {
    onChange(unModifiedValue({ ...modifiedValue, [operator]: [] }))
  }

  function removeItem(operator: string): void {
    const newValue = { ...modifiedValue }
    delete newValue[operator as string]
    onChange(unModifiedValue(newValue))
  }
  
  function updateOperator(oldOperator: string, newOperator): void {
    const newValue = { ...modifiedValue }
    newValue[newOperator] = newValue[oldOperator]
    delete newValue[oldOperator]
    return onChange(unModifiedValue(newValue))
  }
    
  function updateValue(operator: string, data: string[]) {
    return onChange(
      unModifiedValue({
        ...modifiedValue,
        [operator]: data.filter((it) => it !== null), // Tu peux filtrer même si lengh = 0
      })
    )
  }
```

2023-03-06 09:15 UTC, tonai commented on packages/components/src/components/atoms/form/TextFieldTagsMultiple.tsx
> +  }, [optionsListAvailable, operatorValue])
un `useEffect` qui fait `setOperatorValue` et qui dépend de `operatorValue` peut potentiellement générer une boucle infinie.
Si je change `operatorValue`, ça déclenche le `useEffect`, qui fait `setOperatorValue`, donc nouveau render avec `operatorValue` qui a changé, qui déclenche le `useEffect`...etc.
Si ça ne fait pas de boucle infinie, c'est parce que React ne fait pas de nouveau render si tu fais un `setOperatorValue` avec exactement la même valeur (par exemple si tu fais `setOperatorValue(operatorValue)` ça ne fait rien).
Mais dans certains cas ça pourrait poser problème si les références changent...etc.
Le mieux dans ce cas c'est de supprimer la dépendance sur `operatorValue`.
Mais si tu retire la dépendance, tu va avoir `eslint` qui ne va pas être content (et c'est normal).
Pour ce genre de cas tu peux utiliser la version de `setState` sous forme de fonction:
```js
  useEffect(() => {
    setOperatorValue(operatorValue =>
      optionsListAvailable.find(
        (item) => operatorValue?.value === item.value && !item?.disabled
      ) ?? optionsListAvailable.find((item) => !item?.disabled)
    )
  }, [optionsListAvailable])
```

2023-03-06 14:34 UTC, Ponefar commented on packages/components/src/components/atoms/form/TextFieldTagsMultiple.tsx
> +    })
avec le forEach ça donne ça, tu n'as pas besoin de connaitre la longueur du tableau que contient l'index.
    const transformedObject: ITransformedLimitations = {}
    tableau.forEach((item) => {
      if (transformedObject[item.operator]) {
        transformedObject[item.operator].push(item.queryText as string)
      } else {
        transformedObject[item.operator] = [item.queryText as string]
      }
    })
    return transformedObject

2023-03-06 14:39 UTC, Ponefar commented on packages/components/src/components/atoms/form/TextFieldTagsMultiple.tsx
> +  function onChangeModifiedValue(
En effet, j'avais tout mis dans une fonction à la base pour faire comme tu m'avais dit de faire pour les stories. Mais en effet, ce n'est plus necessaire là et beaucoup plus lisible

2023-03-06 14:42 UTC, Ponefar commented on packages/components/src/components/atoms/form/TextFieldTagsMultiple.tsx
> +  }, [optionsListAvailable, operatorValue])
J'avais jamais utilisé cette technique mais dans ce genre de problème c'est trés utile.

2023-03-06 17:06 UTC, tonai approved these changes

2023-03-06 17:08 UTC, merged