fix: grid boost
Elastic-Suite/gally-admin pull request #56
Opened 2023-03-30 17:19 UTC by Ponefar

| Q             | A
| ------------- | ---
| Branch?       | master for features / current stable version branch for bug fixes
| Tickets       | #... 
| License       | OSL-3.0

2023-04-05 09:19 UTC, tonai requested changes

2023-04-05 09:19 UTC, tonai commented on packages/components/src/components/stateful/FieldGuesser/ReadableDropDownGuesser.tsx
> +}
il te manque un `return null` dans le cas où `statuses.current.get(field.property['@id']) !== LoadStatus.SUCCEEDED`

Du coup c'est mieux d'écrire:
```js
if (statuses.current.get(field.property['@id']) !== LoadStatus.SUCCEEDED) {
  return null
}
```

2023-04-05 09:19 UTC, tonai commented on packages/components/src/components/stateful/FieldGuesser/ReadableDropDownGuesser.tsx
> +            return <div key={val}>{val}</div>
Ton `<div>` est nécessaire ?
Si tu souhaites simplement retourner du texte tu peux directement faire `return newDropDownOptions[item] ?? item`

2023-04-05 19:39 UTC, Ponefar commented on packages/components/src/components/molecules/Filters/Filters.tsx
> +    return (label = `${filter?.label}: ${option.label}`)
oui

2023-04-06 08:19 UTC, botisSmile commented on packages/components/public/locales/en/common.json
> +  "false": "No"
Je ne sais pas si c'est une bonne idée de faire ça, on s'enlève le possibilité de traduire "true" par "vrai" et "false" par "faux" dans le futur.

2023-04-06 08:26 UTC, botisSmile commented
Il faut stash tes commits en un seul ou en plusieurs par logique fonctionnelle/technique.
Attention il faudra bien penser à séparer ce qui concerne les boosts et le mécanisme général qui permet de gérer une grid en 2 PR. Le nouveau mécanisme qui permet d'afficher une grid devra être mergé sur la 1.0.x et le code qui serait lié exclusivement aux boosts devra être mergé sur feature-boost. Je n'ai pas l'impression qu'il y ait du code lié au boost, mais je  te laisse vérifier.

2023-04-06 11:23 UTC, closed without merging