es
Elastic-Suite/gally-admin pull request #61
Opened 2023-04-19 02:06 UTC by Ponefar

| Q             | A
| ------------- | ---
| Branch?       | master for features / current stable version branch for bug fixes
| Tickets       | #... 
| License       | OSL-3.0

2023-04-20 13:04 UTC, tonai requested changes

2023-04-20 15:42 UTC, Ponefar commented on packages/shared/src/types/api.ts
> +export interface IFieldSetClass {
ok

2023-04-20 15:43 UTC, Ponefar commented on packages/components/src/components/organisms/CustomForm/CustomForm.tsx
> +  const resource = boostJsLd as IResource
Comment faire pour utiliser le useResource dans le storybook ?
Lorsque je le fais ça me créer un objet comme cela : Object { supportedProperty: undefined }

2023-04-20 15:44 UTC, Ponefar commented on packages/shared/src/types/hydra.ts
> +export interface IFormConfig extends IGallyProperty {
ok

2023-04-20 15:46 UTC, Ponefar commented on packages/components/src/components/organisms/CustomForm/CustomForm.stories.tsx
> +    }
ok

2023-04-20 18:30 UTC, Ponefar commented on packages/components/src/components/organisms/CustomForm/CustomForm.tsx
> +          <div>
non, j'ai changé ce qui posait problème directement dans le editable fieldGuesser

2023-04-20 18:30 UTC, Ponefar commented on packages/components/src/components/organisms/CustomForm/CustomForm.tsx
> +  const resource = boostJsLd as IResource
ok

2023-04-20 18:58 UTC, Ponefar commented on packages/components/src/hooks/useApiForm.ts
> +export function useApiDoubleDatePicker(resource: IResource): IResource {
ok

2023-04-21 16:05 UTC, tonai requested changes

2023-04-21 16:05 UTC, tonai commented on packages/components/src/hooks/useApiTable.ts
> +    return transformedResource.supportedProperty
Pourquoi il y a un `return` après le `return` d'avant ?

2023-04-21 16:05 UTC, tonai commented on packages/components/src/components/organisms/CustomForm/CustomForm.tsx
> +  const headers = useApiHeaders(resource)
Il est passé où ton `useApiHeadersForm` ?

2023-04-21 16:05 UTC, tonai commented on packages/components/src/hooks/useApiTable.ts
> +            })
ça serait probablement plus simple avec un objet qu'avec un array (pas besoin de faire un `findIndex`)

2023-04-25 11:43 UTC, Ponefar commented on packages/components/src/components/organisms/CustomForm/CustomForm.tsx
> +  setData: (val: Record<string, unknown> | undefined) => void
ok

2023-04-25 11:59 UTC, Ponefar commented on packages/components/src/components/organisms/CustomForm/CustomForm.tsx
> +  resourceData: IResource
ok

2023-04-25 12:27 UTC, Ponefar commented on packages/components/src/components/organisms/CustomForm/CustomForm.tsx
> +      const formatDate = { fromDate: response?.from, toDate: response?.to }
Car c'est comme ça que sont nommés  ces champs dans le back ( réponse api de post/ boost)

2023-04-25 12:28 UTC, Ponefar commented on packages/components/src/hooks/useApiForm.ts
> +            '@id': 'https://localhost/docs.jsonld#Boost/doubleDatePicker',
ok

2023-04-25 13:10 UTC, Ponefar commented on packages/components/src/hooks/useApiTable.ts
> +    return transformedResource.supportedProperty
? JE comprends pas ta question, il y a un if au début :     if (transformedResource.gally?.fieldset) {

2023-04-25 13:30 UTC, Ponefar commented on packages/components/src/components/organisms/CustomForm/CustomForm.tsx
> +  const headers = useApiHeaders(resource)
Assemblé dans le useAPiHeaders directement, cela ne servait à rien d'avoir les deux et là c'est plus simple d'utilisation et de maintenabilité.

2023-05-16 08:05 UTC, tonai requested changes

2023-05-16 08:05 UTC, tonai commented on packages/shared/src/services/field.ts
> +  }
si tu fais ça tu ne respecte pas l'ordre des priorités.
Avec ton dev le `mainContext` est prioritaire sur la partie `field.gally?.context`.
Alors que ça doit être l'inverse:
* `field.gally` sont les valeurs par défaut
* `gally[mainContext]` sont des valeurs plus spécifiques (grid ou form)
* `gally?.context` sont les valeurs les plus spécifiques (spécifique à une page donnée)

2023-05-16 08:05 UTC, tonai commented on packages/shared/src/services/field.ts
> +  }
Ajoute des tests unitaires sur cette fonction pour bien vérifier ce fonctionnement

2023-05-17 09:45 UTC, merged