Feat add interface when no boost
Elastic-Suite/gally-admin pull request #98
Opened 2023-06-21 15:38 UTC by adrMeyn

| Q             | A
| ------------- | ---
| Branch?       | master for features / current stable version branch for bug fixes
| Tickets       | #... 
| License       | OSL-3.0

2023-07-05 11:57 UTC, tonai commented on packages/components/src/components/atoms/noAttributes/NoAttributes.tsx
> +export interface INoAttributes {
```suggestion
export interface INoAttributesProps {
```

2023-07-05 11:57 UTC, tonai commented on packages/components/src/components/atoms/noAttributes/NoAttributes.tsx
> +          {realPath ? (
`realPath` n'est pas très parlant, `!external` me parait plus approprié.

2023-07-05 13:24 UTC, Ponefar commented on packages/components/src/components/atoms/noAttributes/NoAttributes.tsx
> +export interface INoAttributes {
corrigé

2023-07-06 06:44 UTC, tonai requested changes

2023-07-06 06:44 UTC, tonai commented on packages/components/src/components/atoms/noAttributes/NoAttributes.tsx
> +          {!external ? (
tu as inversé le `a` le le `Link`.
Si c'est `external` ça veut dire que c'est un lien externe qu'il faut utilisé et donc un `a` au lieu du composant `Link`

2023-07-07 07:53 UTC, tonai approved these changes

2023-07-10 07:48 UTC, merged