Feat 1234599 gestion error form
Elastic-Suite/gally-admin pull request #99
Opened 2023-06-23 14:53 UTC by Ponefar

| Q             | A
| ------------- | ---
| Branch?       | master for features / current stable version branch for bug fixes
| Tickets       | #... 
| License       | OSL-3.0

2023-07-05 12:18 UTC, tonai commented on packages/components/src/components/stateful-pages/ResourceForm/ResourceForm.tsx
> +            err.message
Je trouve ça un peu étrange ton test.
Si tu as à la fois `propertyPath` et `message` tu ajoutes dans `fields`.
Par contre ton else va se déclencher dans ces différents cas:
* si tu n'as que `message` et pas `propertyPath`, dans ce cas tu vas ajouter dans `global[undefined]` ce qui st un peu bizarre
* si tu n'as que `propertyPath` et pas  `message` tu vas ajouter `undefined` dans `global[propertyPath]` ce qui ne semble pas très utile
* si tu n'as ni l'un ni l'autre alors tu ajoutes `undefined` dans `global[undefined]` ce qui est à la fois bizarre et pas très utile.

2023-07-05 12:18 UTC, tonai commented on packages/components/src/components/stateful-pages/ResourceForm/ResourceForm.tsx
> +            err.message
Peut-être que tu pourrais avoir `newErrors.global` qui est un array et tu push dans le array quand tu as un message à ajouter.

2023-07-05 16:13 UTC, Ponefar commented on packages/components/src/components/stateful-pages/ResourceForm/ResourceForm.tsx
> +            err.message
corrigé, en effet, je ne sais pas pourquoi j'ai mis ça comme cela, mais ça fonctionnait. Actuel c'est plus propre.

2023-07-06 06:46 UTC, tonai requested changes

2023-07-06 06:46 UTC, tonai commented on packages/components/src/components/stateful-pages/ResourceForm/ResourceForm.tsx
> +        } else {
Du coup je pense qu'il faudrait ajouter un `else if (err?.message)` ici pour éviter d'afficher une snackbar avec un message vide.

2023-07-07 07:53 UTC, tonai approved these changes

2023-07-10 08:15 UTC, merged